name: edesoft
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons:
  flutter_modular:
  google_fonts:
  mobx:
  flutter_mobx:
  sqflite:
  path_provider:
  intl:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen:
  build_runner:


flutter:

  uses-material-design: true

